# Streamlit Secrets Configuration Template
# Copy this file to .streamlit/secrets.toml and add your API keys
# Note: secrets.toml is automatically ignored by git for security

# Anthropic Claude API Configuration
# Get your API key from: https://console.anthropic.com/
ANTHROPIC_API_KEY = "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"

# Optional: Configure Claude model preferences
ANTHROPIC_MODEL = "claude-4-sonnet-20250514"  # Latest Claude 4 Sonnet model
# Alternative models:
# - "claude-3-sonnet-20240229"  # Balanced performance
# - "claude-3-opus-20240229"    # Highest capability

# Optional: Cost management settings
MAX_MONTHLY_COST = 50.0  # Maximum monthly cost in USD
ENABLE_COST_ALERTS = true

# Optional: Development settings
ENABLE_AI_DEBUG = false
CACHE_AI_RESPONSES = true
