apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1  # Single pod for RWO PVC
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      serviceAccountName: backend-api
      containers:
      - name: backend-api
        image: quay.io/ambient_code/vteam_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "8080"
        - name: STATE_BASE_DIR
          value: "/data/state"
        volumeMounts:
        - name: state-storage
          mountPath: /data/state
        - name: temp-storage
          mountPath: /tmp
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: state-storage
        persistentVolumeClaim:
          claimName: vteam-state-storage
      - name: temp-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
