apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vteam-ambient-runner

# Namespace for all resources (can be overridden with kustomize edit set namespace)
#namespace: ambient-code
namespace: sallyom-vteam

# Resources to include in deployment
resources:
- namespace.yaml
- crds
- rbac
- route.yaml
- git-configmap.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- operator-deployment.yaml
images:
- name: quay.io/ambient_code/vteam_backend:latest
  newName: quay.io/sallyom/vteam-backend
  newTag: latest
- name: quay.io/ambient_code/vteam_claude_runner:latest
  newName: quay.io/ambient_code/vteam_claude_runner
  newTag: latest
- name: quay.io/ambient_code/vteam_frontend:latest
  newName: quay.io/sallyom/vteam-frontend
  newTag: latest
- name: quay.io/ambient_code/vteam_operator:latest
  newName: quay.io/sallyom/vteam-operator
  newTag: latest
