apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vteam-state-storage
  labels:
    app: vteam
    component: state-storage
spec:
  accessModes:
    #- ReadWriteMany  # Prefer RWX if available
    - ReadWriteOnce   # Fallback if RWX not supported
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vteam-shared-workspace-pvc-rwo
  labels:
    app: vteam
    component: shared-workspace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
