apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rhoai-ai-feature-sizing

# Namespace for all resources (can be overridden with kustomize edit set namespace)
namespace: my-custom-namespace

# Resources to include in deployment
resources:
- namespace.yaml
- pvc.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- route.yaml

# Common labels applied to all resources
commonLabels:
  app: rhoai-ai-feature-sizing
  managed-by: kustomize
  version: v1.0.0

# Common annotations applied to all resources
commonAnnotations:
  deployment.kubernetes.io/revision: "1"

# Name prefix for all resources (optional)
# namePrefix: rhoai-

# Images to replace (for different environments)
# Override with: kustomize edit set image quay.io/gkrumbach07/llama-index-demo/rhoai-ai-feature-sizing=your-registry.com/your-image:your-tag
images:
- name: quay.io/gkrumbach07/llama-index-demo/rhoai-ai-feature-sizing
  newName: quay.io/gkrumbach07/llama-index-demo/rhoai-ai-feature-sizing
  newTag: latest

# Configuration patches for different environments

# JSON 6902 patches

# Config map and secret generators (uncomment and create .env.production/.env.secrets files to use)
# Note: When using generators, remove configmap.yaml and secret.yaml from resources list above
# configMapGenerator:
# - envs:
#   - .env.production
#   name: rhoai-env-config

# secretGenerator:
# - envs:
#   - .env.secrets
#   name: rhoai-api-keys
