# Project Custom Resource Definition
# C4 Architecture: Represents multi-tenant projects in vTeam platform
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.vteam.io
spec:
  group: vteam.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
              - description
              - owner
              - quotas
            properties:
              description:
                type: string
                description: Description of the project
              owner:
                type: string
                description: Username of the project owner
              members:
                type: array
                items:
                  type: string
                description: List of project member usernames
              quotas:
                type: object
                required:
                  - maxSessions
                  - maxCpu
                  - maxMemory
                  - maxStorage
                properties:
                  maxSessions:
                    type: integer
                    minimum: 1
                    description: Maximum concurrent sessions
                  maxCpu:
                    type: string
                    pattern: '^[0-9]+(\.[0-9]+)?$'
                    description: Maximum CPU allocation (e.g., "4")
                  maxMemory:
                    type: string
                    pattern: '^[0-9]+(Ki|Mi|Gi)$'
                    description: Maximum memory allocation (e.g., "8Gi")
                  maxStorage:
                    type: string
                    pattern: '^[0-9]+(Ki|Mi|Gi)$'
                    description: Maximum storage allocation (e.g., "100Gi")
              labels:
                type: object
                additionalProperties:
                  type: string
                description: Labels to apply to project resources
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Active", "Failed", "Terminating"]
                description: Current phase of the project
              namespace:
                type: string
                description: Kubernetes namespace created for this project
              activeSessions:
                type: integer
                description: Number of active sessions
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              lastUpdated:
                type: string
                format: date-time
                description: Last update timestamp
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Owner
      type: string
      jsonPath: .spec.owner
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Sessions
      type: integer
      jsonPath: .status.activeSessions
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    categories:
    - vteam
    - all