apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rfeworkflows.vteam.ambient-code
spec:
  group: vteam.ambient-code
  names:
    kind: RFEWorkflow
    listKind: RFEWorkflowList
    plural: rfeworkflows
    singular: rfeworkflow
    shortNames:
    - rfe
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required: [title, description, umbrellaRepo]
            properties:
              title:
                type: string
              description:
                type: string
              umbrellaRepo:
                type: object
                description: "Primary umbrella Git repository"
                required: [url]
                properties:
                  url:
                    type: string
                    description: "Git repository URL"
                  branch:
                    type: string
                    default: "main"
                    description: "Branch to checkout"
              supportingRepos:
                type: array
                description: "Optional supporting Git repositories cloned alongside umbrella repo"
                items:
                  type: object
                  required: [url]
                  properties:
                    url:
                      type: string
                      description: "Git repository URL"
                    branch:
                      type: string
                      default: "main"
                      description: "Branch to checkout"
              workspacePath:
                type: string
              jiraLinks:
                type: array
                description: "Links between workspace files and Jira issues"
                items:
                  type: object
                  required: [path, jiraKey]
                  properties:
                    path:
                      type: string
                      description: "Workspace-relative path to the document"
                    jiraKey:
                      type: string
                      description: "Jira issue key (e.g., PROJ-123)"
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - "Initializing"
                - "Ready"
                default: "Initializing"
              message:
                type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current phase of the RFE workflow
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp

