apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: vteam-backend-alias
    component: backend-alias
spec:
  type: ExternalName
  externalName: vteam-backend.vteam-dev.svc.cluster.local
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
