apiVersion: apps/v1
kind: Deployment
metadata:
  name: vteam-frontend
  labels:
    app: vteam-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vteam-frontend
  template:
    metadata:
      labels:
        app: vteam-frontend
    spec:
      containers:
      - name: frontend
        image: image-registry.openshift-image-registry.svc:5000/vteam-dev/vteam-frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://vteam-backend-vteam-dev.apps-crc.testing/api"
        - name: BACKEND_URL
          value: "http://vteam-backend:8080/api"
        - name: NODE_ENV
          value: "production"
        - name: OC_USER
          value: "developer"
        - name: OC_EMAIL
          value: "developer@vteam-dev.local"
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: frontend-auth-token
              key: token
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vteam-frontend
  labels:
    app: vteam-frontend
spec:
  selector:
    app: vteam-frontend
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vteam-frontend
  labels:
    app: vteam-frontend
spec:
  to:
    kind: Service
    name: vteam-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
