---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vteam-operator
  labels:
    app: vteam-operator
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vteam-operator
  labels:
    app: vteam-operator
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: vteam-operator:latest
