name: Auto-assign Issues to Todo

on:
  issues:
    types: [opened]

permissions:
  issues: write
  repository-projects: write
  contents: read

jobs:
  add-to-project-and-set-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/red-hat-data-services/projects/12
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set issue to Todo status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Issue already added to project by previous step. Todo status assignment handled by GitHub project automation.');
            // Note: The actions/add-to-project action handles the basic addition
            // Additional status field manipulation can be done here if needed
            // but GitHub projects often have their own automation rules