name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: mkdir
      run: mkdir demos/rfe-builder/data

    - name: Log in to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}



    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: demos/rfe-builder
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          quay.io/ambient_code/vteam
          ${{ github.ref != 'refs/heads/main' && format('quay.io/ambient_code/vteam:pr-{0}', github.event.pull_request.number) || '' }}
